export const META_INTERACTIVE_BODY_LIMIT = 1024;
export const META_INTERACTIVE_HEADER_LIMIT = 60;
export const META_INTERACTIVE_FOOTER_LIMIT = 60;
export const META_INTERACTIVE_BUTTON_LIMIT = 20;
export const META_INTERACTIVE_SECTION_TITLE_LIMIT = 24;
export const META_INTERACTIVE_ROW_TITLE_LIMIT = 24;
export const META_INTERACTIVE_ROW_DESCRIPTION_LIMIT = 72;
export const META_MEDIA_CAPTION_LIMIT = 1024;
